# Generated by Django 4.2 on 2023-05-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('desc', models.TextField(max_length=250)),
                ('image', models.CharField(max_length=20)),
                ('skill1', models.CharField(max_length=20)),
                ('skill2', models.CharField(max_length=20)),
                ('skill3', models.CharField(max_length=20)),
                ('skill4', models.CharField(max_length=20)),
                ('skill5', models.CharField(max_length=20)),
                ('skill6', models.CharField(max_length=20)),
            ],
        ),
    ]
