# Generated by Django 4.2 on 2023-06-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIcamModel',
            fields=[
                ('id_img', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.TextField()),
            ],
        ),
    ]
