# Generated by Django 4.2 on 2023-06-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_aicammodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIchatModel',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('chat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id_msg', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('msg', models.TextField()),
            ],
        ),
    ]
